
try {
    console.log(ola)
} catch(err) {
    console.log('erro')
}